language: java

jdk:
  - oraclejdk8

os:
  - linux
  - osx

dist: trusty
osx_image: xcode9.3

env:
  JAVA_OPTS="-Xmx2g -Dfile.encoding=UTF-8"
  DISPLAY=":99.0"
  DBUS_SESSION_BUS_ADDRESS="/dev/null"

addons:
  apt:
    packages:
      - fluxbox
  sonarcloud:
    organization: "hdecarne-github"

git:
  depth: false  

before_script:
  - if [[ -e "./.travis/$TRAVIS_OS_NAME/before_script.sh" ]]; then bash -x ./.travis/$TRAVIS_OS_NAME/before_script.sh; fi
script:
  - ./gradlew --stacktrace clean build

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./gradlew --stacktrace artifactoryPublish sonarqube checkDependencyVersions; fi

notifications:
  slack:
    secure: aUFrxJl9Z/1DezBLZBfOZcJ1NiKYl/jXI323xY+0cABxoGSmwS4MvA9uO81Zko0vquhwprCca5ErnCmyI8L74vI8AmLrBh/HSp+UzDzD35Ie9k1wsLenOUJVyPu7qmf2VJp9oxdoiDO9LoHY+BDJTV8qdKXOnq1UfevDVk+/sn45BTA+M7TUnfWYcQLtFDlFC8+lS2YI7G/Cu3/iV0de7Hzz1kdg4gcvJAfUBu4MLGPT3kYm1fW5Pjd0BOiGcZSbXZFGCR9XjY8eL9IFoxgMPW3DOkOCs8FmbNa7gP2DWAAEJMEkJtOvF41Wuyniv49AGJs51a+AapwMd6vQxFN/GxFJ7osQHJC2azPZYMcKkTZl+phC0gGHcgyN9b7pxJdoJn4XdIHQMrzHlBCM+KtFrqZAYZwYCoL67yQ3K5lIQZDct0h/Gmljt1COwAOzCf+5qGmRaPUK/CvnEyxryBUOgnh+AHvhVrEB3CFwgPpiRvA3ai319hMefjaeVEED7ewfaRfulsReuO77O5rLlaxerDoSVu2C6vkz9ynTfuLBGSfcfuAKJ1xab4Z6cEPoxhfKdebMNAttKwcRGPY8gX6Vsn3BHXdeqnTmYom2zw4rh9RwzpIaQj4/xC66Bx+9W1470KgzYXD0jGcA/mgT0J+7B0QVRV+rN+qdnGfpFfCcvIY=
      
# See https://docs.travis-ci.com/user/languages/java/#caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
